export const paramsWelcome = {
    "particles":{
        "number":{
            "value":60,
            "density":{
                "enable":true,
                "value_area":800
            }
        },"color":{
            "value":"#3d3d3d"
        },
        "shape":{
            "type":"circle",
            "stroke":{
                "width":0,
                "color":"#000000"
            },
            "polygon":{
                "nb_sides":5
            },
            "image":{
                "src":"./leaf.svg",
                "width":100,
                "height":100
            }
        },
        "opacity":{
            "value": 1,
            "random":false,
            "anim":{
                "enable":true,
                "speed":0.8,
                "opacity_min":0.1,
                "sync":false
            }
        },
        "size":{
            "value":2.5,
            "random":true,
            "anim":{
                "enable":false,
                "speed":10,
                "size_min":0.1,
                "sync":false
            }
        },
        "line_linked":{
            "enable":false,
            "distance":150,
            "color":"#3d3d3d",
            "opacity":0.1,
            "width":1
        },
        "move":{
            "enable":true,
            "speed":5,
            "direction":"bottom-left",
            "random":true,
            "straight":false,
            "out_mode":"out",
            "bounce":false,
            "attract":{
                "enable":false,
                "rotateX":600,
                "rotateY":1200
            }
        }
    },
    "interactivity":{
        "detect_on":"window",
        "events":{
            "onhover":{
                "enable":true,
                "mode":"grab"
            },
            "onclick":{
                "enable":true,
                "mode":"repulse"
            },
            "resize":true
        },
        "modes":{
            "grab":{
                "distance":250,
                "line_linked":{
                    "opacity":0.5
                }
            },
            "bubble":{
                "distance":400,
                "size":5,
                "duration":2,
                "opacity":8,
                "speed":3
            },
            "repulse":{
                "distance":200,
                "duration":0.4
            },
            "push":{
                "particles_nb":4
            },
            "remove":{
                "particles_nb":2
            }
        }
    },
    "retina_detect":true
}
